version: "2"
services:
  storage:
   image: busybox
   volumes:
     - /var/lib/mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes_from:
      - storage
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
  rails:
    image: h3poteto/rails:v2.3.3
    env_file: .docker-env
    environment:
      BUNDLE_APP_CONFIG: /usr/src/app/.bundle
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TWITTER_CLIENT_ID: $TWITTER_CLIENT_ID
      TWITTER_CLIENT_SECRET: $TWITTER_CLIENT_SECRET
      TWITTER_ACCESS_TOKEN: $TWITTER_ACCESS_TOKEN
      TWITTER_ACCESS_TOKEN_SECRET: $TWITTER_ACCESS_TOKEN_SECRET
    volumes:
      - ~/.ssh:/home/rails/.ssh
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - redis:redis
      - mysql:mysql
    command: /bin/bash
  sidekiq:
    image: h3poteto/rails:v2.3.3
    env_file: .docker-env
    environment:
      BUNDLE_APP_CONFIG: /usr/src/app/.bundle
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/usr/src/app
    links:
      - redis:redis
      - mysql:mysql
    command: bundle exec sidekiq -C config/sidekiq.yml -e development
