site:
  host: "api.whalebird.org"
  fqdn: "api.whalebird.org"
redis: "localhost:6379"
resque:
  queue: "loop"
  process: 3
  stop_timeout: 10
push:
  certification_path: "certification/server_certificates_sandbox.pem"