site:
  host: "api.whalebird.org"
  fqdn: "api.whalebird.org"
redis:
resque:
  queue: "loop"
  process: 50
  stop_timeout: 10
push:
  certification_path: "certification/server_certificates_production.pem"
